# Generated by Django 5.1 on 2024-08-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../https://res.cloudinary.com/dxfpqnmtu/image/upload/v1723028139/blank_profile_image_mlzrkw.webp', upload_to='images/'),
        ),
    ]
